{"name": "test_add[鍔犳硶娴嬭瘯1]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_cal.py:98: AssumptionFailure\n>>\tpytest.assume(result == exc)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_cal.py:98: AssumptionFailure\nE               >>\tpytest.assume(result == exc)\nE               AssertionError: assert False\n\nc:\\users\\fdd\\envs\\pytest\\lib\\site-packages\\six.py:702: FailedAssumption"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "3"}, {"name": "exc", "value": "4"}], "start": 1615726265123, "stop": 1615726265122, "uuid": "e02b0b58-5ea7-4d2c-9fa5-7064e50674c2", "historyId": "eb8072249c5117292ef26d8c3189be33", "testCaseId": "b07ce6fd6efd62249ca60e5a3c8d5cb9", "fullName": "test_cal.TestCalculator1#test_add", "labels": [{"name": "tag", "value": "flaky(reruns=2, reruns_delay=1)"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCalculator1"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}