{"name": "test_minus[4-7-11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -3 == 11\n  +-3\n  -11", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0D77A00>, a = 4, b = 7, exc = 11\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_minus(self, a, b, exc):\n        result = self.c.minus(a, b)\n>       assert result == exc\nE       assert -3 == 11\nE         +-3\nE         -11\n\ntest_calculator.py:34: AssertionError"}, "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "7"}, {"name": "exc", "value": "11"}], "start": 1615726260940, "stop": 1615726260940, "uuid": "3ecfc536-6bf7-4dd8-92fc-8207c8687540", "historyId": "67a6e6318b00312849779e4cedc2199c", "testCaseId": "7b480cf393e9b022b332fec743686f40", "fullName": "test_calculator.TestCalculator#test_minus", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}