{"name": "test_a[10-20]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 20\n  +10\n  -20", "trace": "self = <test_demo.TestDemo object at 0x0000017CA0F3C2B0>, a = 10, b = 20\n\n    @pytest.mark.parametrize('a,b', [\n        (10, 20),\n        (10, 10),\n        ('a', 'a1')\n    ])\n    def test_a(self, a, b):\n>       assert a == b\nE       assert 10 == 20\nE         +10\nE         -20\n\ntest_demo.py:16: AssertionError"}, "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "20"}], "start": 1615726260891, "stop": 1615726260891, "uuid": "eabe69d6-e18d-4c64-9379-ff305d9dbe3d", "historyId": "2f6fcde460723cb70ef5eee5e698f790", "testCaseId": "804507a742c94cca5d032d6b04dec6b1", "fullName": "test_demo.TestDemo#test_a", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}