{"name": "test_multiple[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "self = <test_cal.TestCalculator1 object at 0x0000017CA0F3C340>, a = 1, b = 2, exc = 3\n\n    @pytest.mark.parametrize('a,b, exc', get_data('data.json')[\"param\"]['mul'])\n    @pytest.mark.flaky(reruns=2, reruns_delay=1)\n    def test_multiple(self, a, b, exc):\n        result = self.c.multiple(a, b)\n>       assert result == exc\nE       assert 2 == 3\nE         +2\nE         -3\n\ntest_cal.py:123: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "exc", "value": "3"}], "start": 1615726263027, "stop": 1615726263028, "uuid": "11c9322e-e01f-41ee-92ad-392cf396a491", "historyId": "05746ebc762de7f0f817a4351711e81a", "testCaseId": "ef795dc53bda406dcfc6ee49655b9649", "fullName": "test_cal.TestCalculator1#test_multiple", "labels": [{"name": "tag", "value": "flaky(reruns=2, reruns_delay=1)"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCalculator1"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}