{"name": "test_add[鍔犳硶娴嬭瘯1]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_cal.py:50: AssumptionFailure\n>>\tpytest.assume(result == exc)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_cal.py:50: AssumptionFailure\nE               >>\tpytest.assume(result == exc)\nE               AssertionError: assert False\n\nc:\\users\\fdd\\envs\\pytest\\lib\\site-packages\\six.py:702: FailedAssumption"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "3"}, {"name": "exc", "value": "4"}], "start": 1615726256649, "stop": 1615726256647, "uuid": "02fc268f-debc-4859-a8e2-1658c022100c", "historyId": "df85bc2a50f1a291e769d05f8292baa9", "testCaseId": "f47f7f9bb9d40fe6ea98144c86389b61", "fullName": "test_cal.TestCalculator#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "flaky(reruns=2, reruns_delay=1)"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}