{"name": "test_minus[2-4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -2 == 5\n  +-2\n  -5", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0F3C6A0>, a = 2, b = 4, exc = 5\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_minus(self, a, b, exc):\n        result = self.c.minus(a, b)\n>       assert result == exc\nE       assert -2 == 5\nE         +-2\nE         -5\n\ntest_calculator.py:34: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "4"}, {"name": "exc", "value": "5"}], "start": 1615726260948, "stop": 1615726260948, "uuid": "94f33fc6-0d86-4249-9e24-9dc9f188be74", "historyId": "3ab2c6ab30d9224b000d470253006d60", "testCaseId": "7b480cf393e9b022b332fec743686f40", "fullName": "test_calculator.TestCalculator#test_minus", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}